---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - git
  - wget
  - zsh
  - go
  - vim

# homebrew cask applications
cask_applications:
  - google-chrome
  - odrive
  - dropbox
  - nylas-mail
  - alfred
  - omnifocus
  - nvalt
  - lastpass
  - tunnelblick
  - vlc
  - the-unarchiver
  - firefox


downloads:
   textexpander:
     name: Textexpander 5
     url: http://dl.smilesoftware.com/com.smileonmymac.textexpander/TextExpander.zip
     dest: "{{general.local_home}}/Downloads/TextExpander.zip"

